package com.confused.anikuta.feature.debugbubble

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.geometry.Offset

/**
 * State holder for the debug bubble (Phase DB).
 *
 * UI state (ephemeral — held in `remember { DebugBubbleState() }`, resets on
 * process restart). The drag position is NOT persisted (D-163) — the bubble
 * returns to its default (bottom-end) every time the app reopens.
 *
 * @property offset The bubble's position in px. Plain [mutableStateOf] — drag
 *           writes are direct (no spring animation; the bubble follows the
 *           finger 1:1).
 * @property expanded Whether the panel is open.
 */
class DebugBubbleState(initialOffset: Offset = Offset.Zero) {
    var offset by mutableStateOf(initialOffset)
        private set
    var expanded by mutableStateOf(false)
        private set

    /** Update the bubble's offset (named updateOffset to avoid a JVM signature
     *  clash with the synthetic setOffset generated by `var offset`.) */
    fun updateOffset(value: Offset) { offset = value }

    fun toggleExpanded() { expanded = !expanded }
    fun collapse() { expanded = false }
    fun expand() { expanded = true }
}
