// CLEAN-ROOM: declarations mirror the CloudStream 3 plugin API surface for binary
// compatibility (interop facts only). All implementations are original ANI-KUTA code.
// No CloudStream source code was copied. See DOCUMENTATION/cloudstream/23-*.md §3.
//
// The repository-protocol models (repo.json → plugins.json → installed records).
// These live in the plugins package upstream; our :data:cloudstream repo client
// reuses them directly for parsing (doc 04 formats).
@file:Suppress("ktlint")

package com.lagradost.cloudstream3.plugins

import com.fasterxml.jackson.annotation.JsonProperty
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

// Different keys for local and online plugins.
const val PLUGINS_KEY = "PLUGINS_KEY"
const val PLUGINS_KEY_LOCAL = "PLUGINS_KEY_LOCAL"

const val EXTENSIONS_CHANNEL_ID = "cloudstream3.extensions"
const val EXTENSIONS_CHANNEL_NAME = "Extensions"
const val EXTENSIONS_CHANNEL_DESCRIPT = "Extension notification channel"

/** This is used as a placeholder / not set version. */
const val PLUGIN_VERSION_NOT_SET = Int.MIN_VALUE

/** This always updates. */
const val PLUGIN_VERSION_ALWAYS_UPDATE = -1

/** Data class for internal storage of installed plugins. */
@Serializable
data class PluginData(
    @JsonProperty("internalName") @SerialName("internalName") val internalName: String,
    @JsonProperty("url") @SerialName("url") val url: String?,
    @JsonProperty("isOnline") @SerialName("isOnline") val isOnline: Boolean,
    @JsonProperty("filePath") @SerialName("filePath") val filePath: String,
    @JsonProperty("version") @SerialName("version") val version: Int,
)

/**
 * One plugins.json entry (doc 04 §3.1 — the 17-field union; jar* fields are the
 * cross-platform twins the Android app ignores but repositories carry).
 */
@Serializable
data class SitePlugin(
    // Url to the .cs3 file
    @JsonProperty("url") @SerialName("url") val url: String,
    // Status to remotely disable the provider: 0 Down, 1 Ok, 2 Slow, 3 Beta only
    @JsonProperty("status") @SerialName("status") val status: Int,
    // Integer over 0, any change of this will trigger an auto update
    @JsonProperty("version") @SerialName("version") val version: Int,
    // Plugin-list schema version (inert at runtime — always 1 in the wild)
    @JsonProperty("apiVersion") @SerialName("apiVersion") val apiVersion: Int,
    // Name to be shown in app
    @JsonProperty("name") @SerialName("name") val name: String,
    // Name to be referenced internally
    @JsonProperty("internalName") @SerialName("internalName") val internalName: String,
    @JsonProperty("authors") @SerialName("authors") val authors: List<String>,
    @JsonProperty("description") @SerialName("description") val description: String? = null,
    // Human-facing source link
    @JsonProperty("repositoryUrl") @SerialName("repositoryUrl") val repositoryUrl: String? = null,
    // TvType enum name tags ("Movie", "TvSeries", "NSFW", …)
    @JsonProperty("tvTypes") @SerialName("tvTypes") val tvTypes: List<String>? = null,
    // Most often a language tag like "en" or "zh-TW"
    @JsonProperty("language") @SerialName("language") val language: String? = null,
    // Supports %size% / %exact_size% placeholders
    @JsonProperty("iconUrl") @SerialName("iconUrl") val iconUrl: String? = null,
    // Automatically generated by the gradle plugin
    @JsonProperty("fileSize") @SerialName("fileSize") val fileSize: Long? = null,
    // sha256-<64 lowercase hex> — verified on download
    @JsonProperty("fileHash") @SerialName("fileHash") val fileHash: String? = null,
)

/** The repo.json model (doc 04 §2.1). */
@Serializable
data class Repository(
    @JsonProperty("iconUrl") @SerialName("iconUrl") val iconUrl: String? = null,
    @JsonProperty("name") @SerialName("name") val name: String,
    @JsonProperty("description") @SerialName("description") val description: String? = null,
    @JsonProperty("manifestVersion") @SerialName("manifestVersion") val manifestVersion: Int,
    @JsonProperty("pluginLists") @SerialName("pluginLists") val pluginLists: List<String>,
)
